analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2592022453900427
  brandStrength: 1
  lightness: 0.5135624825488776
  brandColors:
    - '#FFFFFF'
    - '#6D708F'
    - '#3F3E9C'
    - '#FD594E'
    - '#FF9970'
  rhythmicContrast: 0.5239735923241824
typography_spectrum: 0.2885305
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2132616
favicon: null
name: Aphorisms of Design
